<?php
/**
 *  @package Cumula
 *  @subpackage Templater
 *  @version    $Id$
 */


const TEMPLATER_RENDER = 'templater_render';
const TEMPLATER_PREPARE = 'templater_prepare';
const TEMPLATER_CLEANUP = 'templater_cleanup';
const TEMPLATER_GET_JAVASCRIPT = 'templater_get_javascript';
const TEMPLATER_GET_STYLESHEETS = 'templater_get_stylesheets';
const TEMPLATER_SET_TITLE = 'templater_get_title';
const TEMPLATER_GET_META = 'templater_get_meta';